<?php

/**
 * Created by PhpStorm.
 * User: yoyot
 * Date: 06/12/2016
 * Time: 21:37
 */
class ControllerAdmin extends ControllerUser
{
    function __construct()
    {
        //on démarre ou reprend la session
        session_start();

        try{
            $action=$_REQUEST['action'];
            switch($action){
                case null:
                    $this->Reinit();
                    break;

                case "ajouter titre":

                    break;

                case "supprimer titre":

                    break;

                case "modifier titre":

                    break;

                case "supprimer commentaire":

                    break;
            }
        }catch(PDOException $e){
            //gérer l'exception
        }
    }


    function Reinit()
    {
        parent::Reinit(); // TODO: Change the autogenerated stub
    }
}