<?php

/**
 * Created by PhpStorm.
 * User: yoyot
 * Date: 06/12/2016
 * Time: 21:37
 */
class ControllerAdmin extends ControllerUser
{
    function __construct()
    {
        //on démarre ou reprend la session

        try{
            $action=$_REQUEST['action'];
            switch($action){
                case null:
                    $this->Reinit();
                    break;

                case "ajouterTitre":
                    $this->ajouterTitre();
                    break;

                case "supprimerTitre":
                    $this->supprimerTitre();
                    break;

                case "modifierTitre":
                    $this->modifierTitre();
                    break;

                case "supprimerCommentaire":
                    $this->supprimerCommentaire();
                    break;
            }
        }catch (PDOException $e)
        {
            //si erreur BD, pas le cas ici
            $dVueEreur[] =	"Erreur inattendue!!! ";
            require ($rep.$vues['erreur']);
        }

        catch (Exception $e2)
        {
            $dVueEreur[] =	"Erreur inattendue!!! ";
            require ($rep.$vues['erreur']);
        }

        exit(0);
    }

    function Reinit()
    {
        parent::Reinit(); // TODO: Change the autogenerated stub
    }

    function ajouterTitre() {

    }

    function supprimerTitre() {

    }

    function modifierTitre(){

    }

    function supprimerCommentaire(){

    }


}